export const data = [
  {
    id: 1,
    serialno: 1,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '03:00 - 06:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 2,
    serialno: 2,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 3,
    serialno: 3,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 4,
    serialno: 4,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 5,
    serialno: 5,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 6,
    serialno: 6,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 7,
    serialno: 7,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 8,
    serialno: 8,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 9,
    serialno: 9,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
  {
    id: 10,
    serialno: 10,
    title: 'SGD197: PSLE Problem Solving',
    classLevel: 'primary',
    pricing: 'SGD197',
    classdurationFrom: '01/01/2023',
    classdurationTo: '01/01/2023',
    modeoflearning: 'Online',
    classtime: '3:00-6:00',
    description: 'This is a assignment of a bugs and error company',
  },
];
